### ISSUE TITLE
use postman to post and get new data

### ISSUE THREAD

**Issue by lkhalid0095** [makmn1/ttp-database-assn10#4]

**Comment by Alshohatee** [comment]
postman fetch get all the users.
![image](https://user-images.githubusercontent.com/46002084/150297748-550ea91b-edf0-4fe0-82b2-c97179c70760.png)
![image](https://user-images.githubusercontent.com/46002084/150300433-9b4c1ed1-c9d4-459d-b2b2-f2e7363d7052.png)
